const express=require('express')
const app=express()
const bp=require('body-parser')
const cors=require('cors')
app.use(cors({origin:'http://localhost:3000',credentials:true}))
app.use(bp.json({ limit: "10000kb", extended: true }))
app.use(bp.urlencoded({ limit: "10000kb", extended: true }))
const cookie=require('cookie-parser')
app.use(cookie())
const jwt=require('jsonwebtoken')
const userModel=require('./Models/UserDetails')
const signup=require('./Controllers/Signup')
const signin=require('./Controllers/Signin')
const product=require('./Controllers/Product')
const user=require('./Controllers/User')
const salesReport=require('./Controllers/Sales')
app.use('/',signup)
app.use('/',signin)
app.use('/',product)
app.use('/',user)
app.use('/',salesReport)
app.listen(3002,()=>console.log('Server started!'))